### ISSUE TITLE
While using 3G Faye gives - ZTWebSocketErrorDomain error 2.

### ISSUE THREAD

**Issue by tim-kozak** [pcrawfor/FayeObjC#14]
I'm trying to connect to my server using Vodafone 3G and here is what i getting. wifi and edge working just perfect
Please help me. 3G is critical for my project!

here is my logs

---

Handshake failed The operation couldn’t be completed. (ZTWebSocketErrorDomain error 2.)

---

I'v tried to change - handshake and connect methods in FayeClient.m 
by removing and changing websocket to long-polling. But that didn't worked.
- (void) handshake {
  //    NSArray *connTypes = [NSArray arrayWithObjects:@"long-polling", @"callback-polling", @"iframe", @"websocket", nil];
  NSArray *connTypes = [NSArray arrayWithObjects:@"long-polling", @"callback-polling", @"iframe", nil];
  NSDictionary *dict = [NSDictionary dictionaryWithObjectsAndKeys:HANDSHAKE_CHANNEL, @"channel", @"1.0", @"version", @"1.0beta", @"minimumVersion", connTypes, @"supportedConnectionTypes", nil];
  NSString *json = [dict JSONString];
  [webSocket send:json];  
  }
- (void) connect {
  NSDictionary *dict = [NSDictionary dictionaryWithObjectsAndKeys:CONNECT_CHANNEL, @"channel", self.fayeClientId, @"clientId", @"long-polling", @"connectionType", nil];
  NSString *json = [dict JSONString];  
  [webSocket send:json];
  }

Ask if you need anything. thanks

**Comment by steveluscher** [comment]
Some people with a similar problem believe that this has to do with transparent proxying by the cell network: https://github.com/lukeredpath/libPusher/issues/8. Their solution was to sidestep the problem by encrypting the channel.

Before going to that amount of trouble, why not try the [2_0 branch](https://github.com/pcrawfor/FayeObjC/tree/2_0) of FayeObjC? That version is backed by SocketRocket instead of ZTWebSocket.

**Comment by tim-kozak** [comment]
I've replaced my master FayeObjC with v2_0. but it's still not working with 3G and sopped working with EDGE. i think SSL is the only way for now

**Comment by pcrawfor** [comment]
Hi,

Changing out the protocol wouldn't make any difference since at the moment the client only supports websocket connections. 

I haven't seen this before but it sounds like the websocket connection is getting killed and that is breaking up the handshake/faye connection protocol handling.

What port are you connecting over just out of curiousity?

**Comment by tim-kozak** [comment]
I'm connecting over port 80 to prevent firewalls problems.
I'm getting this error.
<code>Connection failed The operation couldn’t be completed. (ZTWebSocketErrorDomain error 1.)</code>

Does FayeObjC can carry SSL connection? 

<b>I'v generated certificates like this:</b>

Now create the server private key, you'll be asked for a passphrase:
<code>$ openssl genrsa -des3 -out server.key 1024</code>
Create the Certificate Signing Request (CSR):
<code>$ openssl req -new -key server.key -out server.csr</code>
Remove the necessity of entering a passphrase for starting up nginx with SSL using the above private key:

<pre>$ cp server.key server.key.org
$ openssl rsa -in server.key.org -out server.key</pre>

Finally sign the certificate using the above private key and CSR:
<code>$ openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.</code>

<b>Changed listen port options to:</b>

<pre>bayeux.listen(443, {
  key:  'path/to/ssl.key',
  cert: 'path/to/ssl.cert'
});</pre>

<b>Tying connection over 443, i'v also tried wss protocol:</b>
<code>faye = [[FayeClient alloc] initWithURLString:@"ws://domain:443/faye" channel:channel];</code>

**Comment by steveluscher** [comment]
Have you had any luck with this @comonitos?

**Comment by tim-kozak** [comment]
Yeah i switched to long polling client

https://github.com/ddunkin/cometclient there is no issues and interfaces is pretty the same

**Comment by steveluscher** [comment]
OK. I'm bumping up against this problem now.

My findings are that it definitely has to do with [proxying by cellular providers](http://stackoverflow.com/a/5559048/802047). Koodo/Telus in Canada seems to annihilate websocket connections over port 80. I found a great website for testing this; visit [websocketstest.com](http://websocketstest.com) on your 3G connected device.

_Amazingly_ my cell network permits websocket connections on port 443, **even without having SSL configured**. To be clear, I configured my server to respond on an _unencrypted_ port 443 instead of port 80, and it Just Worked™.

Just before closing this issue, I'm going to set up SSL on my Faye endpoint to make sure there's nothing preventing FayeObjC from working over SSL. No time like the present.

**Comment by steveluscher** [comment]
I've just created a free [StartSSL](https://www.startssl.com) certificate, used it to configure a webserver (NginX) to accept SSL connections then proxy them to a Node backend, and have successfully connected to it using the [2_0 branch](https://github.com/pcrawfor/FayeObjC/tree/2_0) of FayeObjC.

If you have any further questions, don't hesitate to ask!
