### ISSUE TITLE
support for http- clients?

### ISSUE THREAD

**Issue by franciscojma86** [pcrawfor/FayeObjC#5]
i noticed the zimt library is no longer supported. also, we are using heroku in the server side, which doesn´t  support web sockets. Is there a way to support http-clients?

**Comment by pcrawfor** [comment]
I've switched over to socket rocket on my 2_0 branch since it is a more actively maintained websocket lib and seems quite good.  

The client doesn't support http based interactions yet, I'm open to pull requests that implement it.  It's possible I'll find some time to do it, but at the moment don't have a pressing use case myself.

It shouldn't be too hard to do the only differences will be in the connection handling and message handling.  So it'd need to add an httpConnect/httpDisconnect and httpSendMessage/httpReceiveMessage.  I'd think this could all be done with NSURLConnection or AFNetworking pretty easily.

**Comment by franciscojma86** [comment]
hi, thanks for the quick answer. I will try to make those changes with AFNetworking. I downloaded you 2_0 branch, and in the FayeClient.m this line is giving me trouble, is there a file missing in the zip?
#import "CCConstants.h"

**Comment by pcrawfor** [comment]
Hey sorry, I just removed that it was leftover from something else I was messing with in my own app.

One thing to keep in mind for the http implementation is the keep-alive on the request or handling reconnection if the connection times out.  Not sure if AFNetworking will handle it for you, it may.

**Comment by franciscojma86** [comment]
but now that you fixed that, a couple of errors show up. Linker errors, should i import more frameworks? i imported libicucore.lib and security.framework, as SocketRocket requires, but still get this error. Any thoughts?
Undefined symbols for architecture i386:
  "_EndianU16_BtoN", referenced from:
      ___36-[SRWebSocket closeWithCode:reason:]_block_invoke_0 in SRWebSocket.o
      -[SRWebSocket handleCloseWithData:] in SRWebSocket.o
      ___block_global_3 in SRWebSocket.o
      -[SRWebSocket _sendFrameWithOpcode:data:] in SRWebSocket.o

**Comment by pcrawfor** [comment]
Hey looks like it could be related to adding the files to the project re: http://stackoverflow.com/questions/6984368/undefined-symbols-for-architecture-i386-objc-class-skpsmtpmessage-refere

**Comment by pcrawfor** [comment]
I'll be updating the sample projects to work with this new version fairly soon as well
